### ISSUE TITLE
友链域名更新请求

### ISSUE THREAD

**Issue by TT2TER** [SurpriseLon/my-website#1]
您好我是“马火星的迷你小屋”的站主，我的博客于近日更新了域名
为：https://blog.1314171.xyz
（请您替换掉原域名blog.mayu8633.tk）

另，您的友链已经被添加在我的博客中

详见链接
https://blog.1314171.xyz/links/

**Comment by Ikun886-cxk** [comment]
抱歉啊现在才看到，已改
